#!/bin/bash

思路：
	由python脚本安装的程序
	$[sudo] python setup.py install
	实际上相当于创建了若干文件
	故要卸载只要删除这些文件即可

方法：
	安装时记录所有创建的文件
	$[sudo] python setup.py --record files.txt #记录安装过程files.txt
	卸载时删除所有被创建的文件
	#cat files.txt | xargs rm -rf

Run:
	geeknote未安装前找不到“geeknote“命令
	安装后可以找到命令
	卸载后又找不到命令 #说明卸载成功
